print("Hi! This program will generate a band name for you.\n")
city = input("What city did you grow up in?\n")
pet = input("What is the name of a pet?\n")
print("\nThe name of your band is: " + city + " " + pet)
input("\nPress Enter to Exit...")