question_data = [

            {
                "category": "Animals",
                "type": "boolean",
                "difficulty": "easy",
                "question": "The Axolotl is an amphibian that can spend its whole life in a larval state.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "Science: Computers",
                "type": "boolean",
                "difficulty": "medium",
                "question": "The HTML5 standard was published in 2014.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "Vehicles",
                "type": "boolean",
                "difficulty": "hard",
                "question": "In 1993 Swedish car manufacturer Saab experimented with replacing the steering wheel with a joystick in a Saab 9000.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "Mythology",
                "type": "boolean",
                "difficulty": "easy",
                "question": "In Norse mythology, Thor once dressed as a woman.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "Entertainment: Film",
                "type": "boolean",
                "difficulty": "easy",
                "question": "Han Solo&#039;s co-pilot and best friend, &quot;Chewbacca&quot;, is an Ewok.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "category": "Geography",
                "type": "boolean",
                "difficulty": "medium",
                "question": "Seoul is the capital of North Korea.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "category": "Entertainment: Video Games",
                "type": "boolean",
                "difficulty": "easy",
                "question": "The song &quot;Megalovania&quot; by Toby Fox made its third appearence in the 2015 RPG &quot;Undertale&quot;.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "Science: Mathematics",
                "type": "boolean",
                "difficulty": "medium",
                "question": "The Pythagorean theorem states that the square of the hypotenuse is equal to the product of the squares of the other two sides.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "category": "General Knowledge",
                "type": "boolean",
                "difficulty": "medium",
                "question": "&quot;Typewriter&quot; is the longest word that can be typed using only the first row on a QWERTY keyboard.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "Entertainment: Music",
                "type": "boolean",
                "difficulty": "medium",
                "question": "The cover of The Beatles album &quot;Abbey Road&quot; featured a Volkswagen Beetle in the background.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "Geography",
                "type": "boolean",
                "difficulty": "medium",
                "question": "The surface area of Russia is slightly larger than that of the dwarf planet Pluto.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "General Knowledge",
                "type": "boolean",
                "difficulty": "easy",
                "question": "Gumbo is a stew that originated in Louisiana.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "Geography",
                "type": "boolean",
                "difficulty": "easy",
                "question": "San Marino is the only country completely surrounded by another country.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "category": "Entertainment: Board Games",
                "type": "boolean",
                "difficulty": "medium",
                "question": "In the game &quot;Racko&quot; you may pick up ANY card from the discard pile.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "category": "Animals",
                "type": "boolean",
                "difficulty": "medium",
                "question": "&quot;Kamea,&quot; the Gilbertese Islander word for dog, is derived from the English phrase &quot;Come here!&quot;",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "History",
                "type": "boolean",
                "difficulty": "medium",
                "question": "&quot;I disapprove of what you say, but I will defend to the death your right to say it&quot; is a quote from French philosopher Voltaire.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "category": "Entertainment: Video Games",
                "type": "boolean",
                "difficulty": "easy",
                "question": "Faust is a playable character in &quot;Guilty Gear Xrd Revelator&quot;.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "Entertainment: Video Games",
                "type": "boolean",
                "difficulty": "easy",
                "question": "Luigi is taller than Mario?",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "Science: Computers",
                "type": "boolean",
                "difficulty": "medium",
                "question": "&quot;Windows NT&quot; is a monolithic kernel.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "category": "General Knowledge",
                "type": "boolean",
                "difficulty": "easy",
                "question": "A scientific study on peanuts in bars found traces of over 100 unique specimens of urine.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "category": "Entertainment: Film",
                "type": "boolean",
                "difficulty": "medium",
                "question": "The Xenomorph from the science fiction film &quot;Alien&quot; has acidic blood.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "Mythology",
                "type": "boolean",
                "difficulty": "medium",
                "question": "According to Norse mythology, Loki is a mother.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "General Knowledge",
                "type": "boolean",
                "difficulty": "medium",
                "question": "The term &quot;Spam&quot; came before the food product &quot;Spam&quot;.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "category": "Entertainment: Video Games",
                "type": "boolean",
                "difficulty": "easy",
                "question": "The ultimate phrase used by Pharah from Overwatch is: &quot;Justice rains from above!&quot;",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "Entertainment: Japanese Anime & Manga",
                "type": "boolean",
                "difficulty": "medium",
                "question": "The anime Attack on Titan was directed by Tetsur\u014d Araki, the same person who directed the anime Highschool of the Dead.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "Entertainment: Video Games",
                "type": "boolean",
                "difficulty": "easy",
                "question": "Danganronpa 2: Goodbye Despair featured all of the surviving students from the first game.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "Entertainment: Books",
                "type": "boolean",
                "difficulty": "easy",
                "question": "Stephen Chbosky wrote the book &#039;The Perks of Being A Wallflower&#039;.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "Science: Computers",
                "type": "boolean",
                "difficulty": "easy",
                "question": "&quot;HTML&quot; stands for Hypertext Markup Language.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "Animals",
                "type": "boolean",
                "difficulty": "medium",
                "question": "The Platypus is a mammal.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "General Knowledge",
                "type": "boolean",
                "difficulty": "easy",
                "question": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "Entertainment: Music",
                "type": "boolean",
                "difficulty": "easy",
                "question": "A Saxophone is a brass instrument.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "category": "Science & Nature",
                "type": "boolean",
                "difficulty": "easy",
                "question": "An Astronomical Unit is the distance between Earth and the Moon.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "category": "General Knowledge",
                "type": "boolean",
                "difficulty": "medium",
                "question": "Fast food restaurant chains Carl&#039;s Jr. and Hardee&#039;s are owned by the same company.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "Sports",
                "type": "boolean",
                "difficulty": "easy",
                "question": "In association football, or soccer, a corner kick is when the game restarts after someone scores a goal.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "category": "Entertainment: Music",
                "type": "boolean",
                "difficulty": "medium",
                "question": "Pink Guy&#039;s debut album was &quot;Pink Season&quot;.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "category": "Mythology",
                "type": "boolean",
                "difficulty": "medium",
                "question": "The Roman god &quot;Jupiter&quot; was first known as &quot;Zeus&quot; to the Greeks.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "Entertainment: Video Games",
                "type": "boolean",
                "difficulty": "medium",
                "question": "The ADAM collecters in the Bioshock series are known as Little Sisters.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "Politics",
                "type": "boolean",
                "difficulty": "medium",
                "question": "Helen Clark was the 37th Prime Minister of Australia.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "category": "Entertainment: Film",
                "type": "boolean",
                "difficulty": "easy",
                "question": "Actor Tommy Chong served prison time.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "General Knowledge",
                "type": "boolean",
                "difficulty": "easy",
                "question": "Scotland voted to become an independent country during the referendum from September 2014.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "category": "Entertainment: Video Games",
                "type": "boolean",
                "difficulty": "easy",
                "question": "Several characters in &quot;Super Mario 64&quot; blink their eyes, including Mario himself.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "History",
                "type": "boolean",
                "difficulty": "easy",
                "question": "The United States of America was the first country to launch a man into space.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "category": "Entertainment: Film",
                "type": "boolean",
                "difficulty": "medium",
                "question": "The movie &quot;Tron&quot; received an Oscar nomination for Best Visual Effects.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "category": "Entertainment: Cartoon & Animations",
                "type": "boolean",
                "difficulty": "medium",
                "question": "Night on Bald Mountain was one of the musical pieces featured in Disney&#039;s 1940&#039;s film Fantasia.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "Entertainment: Cartoon & Animations",
                "type": "boolean",
                "difficulty": "medium",
                "question": "Blue Danube was one of the musical pieces featured in Disney&#039;s 1940&#039;s film Fantasia.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "category": "Entertainment: Music",
                "type": "boolean",
                "difficulty": "medium",
                "question": "A Facebook campaign placed Rage Against The Machine&#039;s &quot;Killing in the Name Of&quot; as the UK Christmas Number 1 in 2009.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "Art",
                "type": "boolean",
                "difficulty": "medium",
                "question": "Venus of Willendorf is one of the earliest works of art, depicting the planets Mars and Venus embrace in the heavens at night.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "category": "Entertainment: Music",
                "type": "boolean",
                "difficulty": "medium",
                "question": "Metallica collaborated with Rowan Atkinson&#039;s Mr Bean on a 1992 comic relief single.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "category": "Entertainment: Video Games",
                "type": "boolean",
                "difficulty": "easy",
                "question": "Codemasters is the developer of the Gran Turismo series.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "category": "Entertainment: Video Games",
                "type": "boolean",
                "difficulty": "easy",
                "question": "There are 2 player roles in Trouble in Terrorist Town.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
]